spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/jobdb
spring.datasource.username = postgres
spring.datasource.password = Admin@123

jpa.hibernate.ddl-auto = update
jpa.hibernate.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port = 8080


#spring.data.elasticsearch.cluster-name = elasticsearch
#spring.data.elasticsearch.cluster-nodes: localhost:9200
